version: "1"
services:
  web:
    image: "node:14"
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    env:
      - NODE_ENV=production
      - PORT=3000
    command: "npm start"
